POST https://us-central1-involvement-api.cloudfunctions.net/capstoneApi/apps/

####
https://us-central1-involvement-api.cloudfunctions.net/capstoneApi/apps/HXiyRBssDCt7xgEOUDxr/likes

####
POST https://us-central1-involvement-api.cloudfunctions.net/capstoneApi/apps/RJjXXfLZVNow7n5VSnHJ/likes HTTP/1.1
Content-Type: application/json

<request>
{
    "item_id": "1"
}
</request>

####
http://api.tvmaze.com/shows/1/episodes?specials=1

####
https://us-central1-involvement-api.cloudfunctions.net/capstoneApi/apps/HXiyRBssDCt7xgEOUDxr/comments?item_id=39